{% set name = "fractal-client" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fractal_client-{{ version }}.tar.gz
  sha256: 5d24f481339d0d2431177214b2d4b11fbccfeb15523f5d477edef94be4080810

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - fractal = fractal_client.__main__:run
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - python-dotenv >=0.20.0,<0.21.0
    - rich >=12.5.1,<13.0.0
    - httpx >=0.23.0,<0.24.0
    - pyjwt >=2.4.0,<3.0.0
    - packaging >=23.1.0,<24.0.0

test:
  imports:
    - fractal_client
  commands:
    - pip check
    - fractal --help
  requires:
    - pip

about:
  home: https://github.com/fractal-analytics-platform/fractal-client
  summary: Client component of the Fractal analytics platform
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ychiucco
    - jluethi
    - mfranzon
    - tcompa
